use employee;

-- ASSIGNMENT ON TYPES OF SUB QUERY
-- 1.WAQTD NAME OF THE EMPLOYEES EARNING SALARY MORE THAN THE SALESMAN
SELECT Ename 
FROM emp
WHERE Sal > ALL (SELECT Sal FROM emp WHERE Job = 'SALESMAN');


-- 2.WAQTD DETAILS OF THE EMPLOYEES HIRED AFTER ALL THE CLERKS
SELECT * 
FROM emp
WHERE HireDate > ALL (SELECT HireDate FROM emp WHERE Job = 'CLERK');


-- 3.WAQTD NAME AND SALARY FOR ALL THE EMPLOYEES IF THEY ARE EARNING LESS THAN ATLEAST A MANAGER
SELECT Ename , Sal
FROM emp
WHERE Sal < ANY (SELECT Sal FROM emp WHERE Job = 'Manager');


-- 4.WAQTD NAME AND HIREDATE OF EMPLOYEES HIRED BEFORE ALL THE MANAGERS
SELECT Ename, HireDate
FROM emp 
WHERE HireDate < ALL (SELECT HireDate FROM emp WHERE Job = 'Manager');


-- 5.WAQTD NAMES OF THE EMPLOYEES HIRED AFTER ALL THE MANAGERS AND EARNING SALARY MORE THAN ALL THE CLERKS
SELECT Ename 
FROM emp 
WHERE HireDate > ALL (SELECT HireDate FROM emp WHERE Job ='Manager' AND 
           Sal > All (SELECT Sal FROM emp WHERE Job ='Clerk'));


-- 6.WAQTD DETAILS OF THE EMPLOYEES WORKING AS CLERK AND HIRED BEFORE ATLEST A SALESMAN.
SELECT * 
FROM emp 
WHERE Job = 'Clerk' AND HireDate < ANY (SELECT HireDate FROM emp WHERE Job = 'Salesman');


-- 7.WAQTD DETAILS OF EMPLOYEES WORKING IN ACCOUNTING OR SALES DEPT
SELECT * 
FROM emp 
WHERE DeptNo IN (SELECT DeptNo FROM dept WHERE DName IN ('ACCOUNTING', 'SALES'));


-- 8.WAQTD DEPARTMENT NAMES OF THE EMPOYEES WITH NAME SMITH, KING AND MILLER
SELECT DName 
FROM Dept 
WHERE DeptNo IN (SELECT DeptNo FROM emp WHERE EName IN ('SMITH','KING','MILLER'));

-- 9.WAQTD DETAILS OF EMPLOYEES WORKING NEWYORK OR CHICAGO
SELECT * 
FROM emp
WHERE DeptNo = (SELECT DeptNo FROM dept WHERE Loc IN ('NEWYORK','CHICAGO')); 

-- 10.WAQTD EMP NAMES IF EMPLOYEES ARE HIRED AFTER ALL THE EMPLOYEES OF DEPT 10
SELECT Ename 
FROM emp 
WHERE HireDate > ALL (SELECT HireDate FROM emp WHERE DeptNo = 10);




---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



-- ASSIGNMENT ON NESTED SUB QUERY :

-- 1.WAQTD 2ND MINIMUM SALARY
SELECT Sal 
FROM emp 
ORDER BY Sal ASC
LIMIT 1,1;


SELECT MIN(Sal)
FROM emp 
WHERE SAL > (SELECT MIN(Sal) FROM emp);


-- 2.WAQTD 5TH MAXIMUM SALARY
SELECT Sal
FROM emp
ORDER BY Sal DESC
LIMIT 4,1; 

-- 3. WAQTD NAME OF THE EMPLOYEE EARNING 3RD MAXIMUM SALARY
SELECT Ename, Sal
FROM emp
ORDER BY Sal DESC
LIMIT 2,1;


-- 4.WAQTD EMPNO OF THE EMPLOYEE EARNING 2NDMAXIMUM SALARY
SELECT EmpNo
FROM emp
ORDER BY Sal DESC
LIMIT 1,1;

-- 5.WAQTD DEPARTMENT NAME OF AN EMPLOYEE GETTING 4TH MAX SAL
SELECT DName 
FROM dept 
WHERE DeptNo = (SELECT DeptNo FROM emp ORDER BY SAL DESC LIMIT 3,1);


-- 6.WAQTD DETAILS OF THE EMPLOYEE WHO WAS HIRED 2nd
SELECT * 
FROM emp 
ORDER BY HireDate ASC 
LIMIT 1,1 ;

-- 7.WAQTD NAME OF THE EMPLOYEE HIRED BEFORE THE LAST EMPLOYEE
SELECT EName
FROM emp
ORDER BY  HireDate DESC
LIMIT 1,1 ; 

-- 8.WAQTD LOC OF THE EMPLOYEE WHO WAS HIRED FIRST
SELECT Loc
FROM Dept 
WHERE DeptNo IN (SELECT DeptNo FROM emp ORDER BY HireDate DESC);



-- 9.WAQTD DETAILS OF THE EMPLOYEE EARNING 7TH MINIMUM SALARY
SELECT * 
FROM emp
ORDER BY Sal ASC 
LIMIT 6,1 ;


-- 10.WAQTD DNAME OF EMPLOYEE GETTING 2ND MAXIMUM SALARY
SELECT Dname 
FROM dept 
WHERE DeptNo = (SELECT DeptNo
 FROM emp 
 ORDER BY Sal DESC
 LIMIT 1,1) ;