use employee;
-- ASSIGNMENT ON CASE 1:

-- 1. WAQTD NAME AND DEPTNO OF THE EMPLOYEES IF THEY ARE WORKING IN THE SAME DEPT AS JONES.
SELECT EName, DeptNo
FROM emp
WHERE DeptNo = (SELECT DeptNo FROM emp  WHERE EName = 'JONES');


-- 2. WAQTD NAME AND JOB OF ALL THE EMPLOYEES WORKING IN THE SAME DESIGNATION AS JAMES.
SELECT EName, Job
FROM emp
WHERE Job = (SELECT Job FROM emp  WHERE EName = 'JAMES');


-- 3. WAQTD EMPNO AND ENAME ALONG WITH ANNUAL SALARY OF ALL THE EMPLOYEES IF THEIR ANNUAL SALARY IS GREATER THAN WARDS ANNUAL SALARY.
SELECT EmpNo, EName, SAL*12 AS "Annual Salary"
FROM emp
Where Sal*12 > (SELECT Sal*12 FROM emp where ename = 'WARD');


-- 4. WAQTD NAME AND HIREDATE OF THE EMPLOYEES IF THEY ARE HIRED BEFORE SCOTT.
SELECT Ename, HireDate
FROM emp
WHERE HIREDATE < (SELECT HireDate FROM emp WHERE EName = 'SCOTT'); 


-- 5. WAQTD NAME AND HIREDATE OF THE EMPLOYEES IF THEY ARE HIRED AFTER THE PRESIDENT.
SELECT EName, HireDate
FROM emp
WHERE HireDate > (SELECT HireDate FROM emp Where Job In ('PRESIDENT')); 


-- 6. WAQTD NAME AND SAL OF THE EMPLOYEE IF THEY ARE EARNING SAL LESS THAN THE EMPLOYEE WHOS EMPNO IS 7839.
 SELECT EName, Sal
FROM emp
WHERE Sal < (SELECT Sal FROM emp Where EmpNO = 7839) ; 


-- 7. WAQTD ALL THE DETAILS OF THE EMPLOYEES IF THE EMPLOYEES ARE HIRED BEFORE MILLER.
SELECT * 
FROM emp 
WHERE Hiredate < (SELECT HireDate FROM emp WHERE Ename = 'MILLER');


-- 8. WAQTD ENAME AND EMPNO OF THE EMPLOYEES IF EMPLOYEES ARE EARNING MORE THAN ALLEN.
SELECT Ename, EmpNo
FROM emp 
WHERE Sal > (Select Sal FROM emp Where Ename = 'Allen');


-- 9. WAQTD ENAME AND SALARY OF ALL THE EMPLOYEES WHO ARE EARNING MORE THAN MILLER BUT LESS THAN ALLEN.
SELECT Ename, Sal
FROM emp 
WHERE Sal > (SELECT Sal FROM emp WHERE EName = 'MILLER') AND 
      Sal < (SELECT Sal FROM emp WHERE EName = 'Allen');


-- 10. WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING IN DEPT 20 AND WORKING IN THE SAME DESIGNATION AS SMITH.
SELECT * FROM emp
WHERE DeptNo = 20 AND Job = (SELECT Job From emp WHERE Ename ='SMITH');


-- 11. WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE SAME DEPT.AS TURNER.
SELECT * FROM emp 
WHERE Job = 'MANAGER' AND DeptNo = (SELECT DeptNo From emp WHERE EName = 'TURNER');


-- 12. WAQTD NAME AND HIREDATE, OF THE EMPLOYEES HIRED AFTER 1980 AND BEFORE KING.
SELECT Ename, HireDate 
FROM emp 
WHERE HIREDATE > '1980-12-31' AND HireDate < (SELECT HireDate FROM emp WHERE EName = 'KING');


-- 13. WAQTD NAME AND SAL ALONG WITH ANNUAL SAL FOR ALL EMPLOYEES WHOS SAL IS LESS THAN BLAKE AND MORE THAN 3500.
SELECT Ename ,Sal, Sal*12 
FROM emp
WHERE Sal < (SELECT Sal FROM emp WHERE Ename = 'BLAKE') AND Sal > 3500 ;


-- 14. WAQTD ALL THE DETAILS OF EMPLOYEES WHO EARN MORE THAN SCOTT BUT LESS THAN KING.
SELECT *
FROM emp 
WHERE Sal > (SELECT Sal FROM emp WHERE EName = 'SCOTT') AND
      Sal < (SELECT Sal FROM emp WHERE EName = 'KING');


      
-- 15. WAQTD NAME OF THE EMPLOYEES WHOS NAME STARTS WITH 'A' AND WORKS IN THE SAME DEPT AS BLAKE.
SELECT EName 
FROM emp 
WHERE Ename LIKE 'A%' AND EName ='BLAKE' AND DeptNO = (SELECT DeptNO FROM Dept);



-- 16. WAQTD NAME AND COMM IF EMPLOYEES EARN COMISSION AND WORK IN THE SAME DESIGNATION AS SMITH.
SELECT Ename, COMM
FROM emp
WHERE COMM IS NOT NULL AND Job = (SELECT JOB FROM emp WHERE EName ='SMITH') ;


-- 17. WAQTD DETAILS OF ALL THE EMPLOYEES WORKING AS CLERK IN THE SAME DEPT AS TURNER.
SELECT * 
FROM emp 
WHERE JOB = 'CLERK' AND DeptNo = (SELECT DeptNo FROM emp WHERE EName = 'TURNER');


-- 18. WAQTD ENAME, SAL AND DESIGNATION OF THE EMPLOYEES WHOS ANNUAL SALARY IS MORE THAN SMITH AND LESS THAN KING.
SELECT Ename, SAl, Job 
FROM emp 
WHERE Sal*12 > (SELECT Sal*12 FROM emp WHERE EName = 'SMITH') AND
      Sal*12 < (SELECT Sal*12 FROM emp WHERE EName = 'KING');        




-- ASSIGNMENT ON CASE 2:

-- 1. WAQTD DNAME OF THE EMPLOYEES WHOS NAME IS SMITH.
SELECT DName 
From dept 
WHERE DeptNo = (SELECT DeptNo FROM emp WHERE EName = 'SMITH');


-- 2. WAQTD DNAME AND LOC OF THE EMPLOYEE WHOS ENAME IS KING.
SELECT DName, Loc 
FROM Dept 
WHERE DeptNo = (SELECT DeptNo FROM emp WHERE EName = 'KING');


-- 3. WAQTD LOC OF THE EMP WHOS EMPLOYEE NUMBER IS 7902.
SELECT Loc
FROM Dept
 WHERE DeptNo = (SELECT DeptNO FROM emp WHERE EmpNo = 7902) ;


-- 4. WAQTD DNAME AND LOC ALONG WITH DEPTNO OF THE EMPLOYEE WHOS NAME ENDS WITH 'R'.
SELECT Dname, Loc, DeptNo
FROM dept
WHERE DeptNo IN (SELECT DeptNo FROM emp WHERE EName LIKE '%R');


-- 5. WAQTD DNAME OF THE EMPLOYEE WHOS DESIGNATION IS PRESIDENT.
SELECT Dname 
FROM dept
WHERE DeptNo = (SELECT DeptNo FROM emp WHERE Job = 'PRESIDENT');


-- 6. WAQTD NAMES OF THE EMPLOYEES WORKING IN ACCOUNTING DEPARTMENT.
SELECT Ename 
FROM emp
WHERE DeptNo =(SELECT DeptNo FROM dept Where DName = 'ACCOUNTING');


-- 7. WAQTD ENAME AND SALARIES OF THE EMPLOYEES WHO ARE WORKING IN THE LOCATION CHICAGO.
SELECT Ename, Sal
FROM emp 
WHERE DeptNo = (SELECT DeptNo FROM dept WHERE Loc = 'CHICAGO');


-- 8. WAQTD DETAILS OF THE EMPLOYEES WORKING IN SALES.
SELECT * FROM emp 
WHERE DeptNo = (SELECT DeptNo FROM dept WHERE Dname = 'Sales');


-- 9. WAQTD DETAILS OF THE EMP ALONG WITH ANNUAL SALARY IF EMPLOYEES ARE WORKING IN NEW YORK.
SELECT *, Sal*12 FROM emp
Where DeptNo = (SELECT DeptNo From dept Where Loc = 'NEW York');


-- 10. WAQTD NAMES OF EMPLOYEES WORKING IN OPERATIONS DEPARTMENT.
SELECT Ename FROM emp 
WHERE DeptNo = (SELECT DeptNo FROM dept WHERE DName = 'Operations');










