use Employee;

-- Group By Clause Practice

-- 1.WAQTD NUMBER OF EMPLOYEES WORKING IN EACH DEPARTEMENT EXCEPT PRESIDENT.
SELECT COUNT(*), DeptNo
FROM emp
WHERE Job NOT IN ('PRESIDENT')
GROUP BY DeptNo;


-- 2.WAQTD TOTAL SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH JOB.
SELECT SUM(Sal), Job
FROM emp
GROUP BY Job;


-- 3.WAQTD NUMBER OF EMPLOYEEES WORKING AS MANAGER IN EACH DEPARTMENT.
SELECT COUNT(*), DeptNo 
FROM emp
WHERE Job IN ('Manager')
GROUP BY DeptNo;


-- 4. WAQTD AVG SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH DEPARTMENT EXCLUDING THE EMPLOYEES OF DEPTNO 20.
SELECT Avg(Sal), DeptNo
FROM emp
WHERE DeptNo NOT IN (20)
GROUP BY DeptNo;


-- 5.WAQTD NUMBER OF EMPLOYEES HAVING CHARACTER 'A' IN THEIR NAMES IN EACH JOB.
SELECT COUNT(*), Job
FROM emp
WHERE Ename LIKE '%A%'
GROUP BY Job;


-- 6.WAQTD NUMBER OF EMPLOYEES AND AVG SALARY NEEDED TO PAY THE EMPLOYEES WHO SALARY IN GREATER THAN 2000 IN EACH DEPT.
SELECT COUNT(*), Avg(Sal), DeptNo
FROM emp
WHERE Sal > 2000
GROUP BY DeptNo;


-- 7.WAQDTD TOTAL SALARY NEEDED TO PAY AND NUMBER OF SALESMANS IN EACH DEPT.
SELECT SUM(Sal), COUNT(JOB), DeptNo
FROM emp
WHERE Job IN ('Salesman')
GROUP BY DeptNo; 


-- 8. WAQTD NUMBER OF EMPLOYEES WITH THEIR MAXIMUM SALARIES IN EACH JOB.
SELECT COUNT(*), MAX(Sal), Job
FROM emp
GROUP BY Job;


-- 9.WAQTD MAXIMUM SALARIES GIVEN TO AN EMPLOYEE WORKING IN EACH DEPT.
SELECT MAX(Sal), DeptNo
FROM emp
GROUP BY DeptNo ;


-- 10.WAQTD NUMBER OF TIMES THE SALARIES PRESENT IN EMPLOYEE TABLE.
SELECT COUNT(Sal), Sal
FROM emp
GROUP By Sal;




-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------




-- Having Clause Practice
-- 1. WAQTD DNO AND NUMBER OF EMP WORKING IN EACH DEPT IF THERE ARE ATLEAST 2 CLERKS IN EACH DEPT
SELECT DeptNo, COUNT(*)
FROM emp
WHERE Job IN ('Clerk')
GROUP BY DeptNo
HAVING COUNT(Job) <= 2;


-- 2. WAQTD DNO AND TOTAL SAALARY NEEDED TO PAY ALL EMP IN EACH DEPT IF THERE ARE ATLEAST 4 EMP IN EACH DEPT
SELECT DeptNo, SUM(Sal)
FROM emp
GROUP BY DeptNo
HAVING COUNT(EName) <= 4; 


-- 3.WAQTD NUMBER OF EMP EARNING SAL MORE THAN 1200 IN EACH JOB AND THE TOTAL SAL NEEDED TO PAY EMP OF EACH JOB MUST EXCEES 3800
SELECT COUNT(*), SUM(SAL), JOB
FROM emp
WHERE SAL > 1200
GROUP BY JOB
HAVING SUM(SAL) > 3800 ;


-- 4.WAQTD DEPTNO AND NUMBER OF EMP WORKING ONLY IF THERE ARE 2 EMP WORKING IN EACH DEPT AS MANAGER
SELECT DeptNo , COUNT(*)
FROM emp 
WHERE Job IN ('Manager')
GROUP BY DeptNo
HAVING COUNT(EName) = 2 ;


-- 5.WAQTD JOB AND MAX SAL OF EMP IN EACH JOB IF THE MAX SAL EXCEEDS 2600
SELECT Job, Max(Sal)
FROM emp
GROUP BY JOB
HAVING MAX(Sal) > 2600 ;


-- 6. WAQTD THE SALARIES WHICH ARE REPEATED IN EMP TABLE
SELECT Sal,Count(Sal)
FROM emp
GROUP BY Sal
HAVING COUNT(Sal) > 1 ; 


-- 7.WAQTD THE HIREDATE WHICH ARE DUPLICATED IN EMP TABLE
SELECT HireDate
FROM emp
GROUP BY Hiredate
HAVING COUNT(HireDate) > 1 ;


-- 8.WAQTD AVG SALARY OF EACH DEPT IF AVG SAL IS LESS THAN 3000
SELECT Avg(Sal), DeptNo
FROM emp
GROUP BY DeptNo
HAVING AVG(Sal) < 3000 ;


-- 9.WAQTD DEPTNO IF THERE ARE ATLEAST 3 EMP IN EACH DEPT WHOS NAME HAS CHAR 'A' OR 'S'
SELECT DeptNo,Count(EName)
FROM emp
WHERE EName LIKE '%A%' AND Ename Like'%S%'
GROUP BY DeptNo
HAVING COUNT(EName) <= 3 ;


-- 10.WAQTD MIN AND MAX SALARIES OF EACH JOB IF MIN SAL IS MORE THAN 1000 AND MAX SAL IS LESS THAN 5000.
SELECT MIN(Sal), MAX(Sal), Job
FROM emp
GROUP BY JOB
HAVING Min(Sal) > 1000 AND  MAX(Sal) < 5000 ;