use employee;

-- ASSIGNMENT ON SELF JOIN :
-- 1.WAQTD NAME OF THE EMPLOYEE AND HIS MANAGER'S NAME IF EMPLOYEE IS WORKING AS CLERK
SELECT E1.Ename, E2.Ename
FROM emp e1 , emp e2
WHERE e1.MGR = e2.EmpNo AND E1.JOB = "Clerk";


-- 2.WAQTD NAME OF THE EMPLOYEE AND MANAGER'S DESIGNATION IF MANAGER WORKS IN DEPT 10 OR 20
SELECT E1.Ename , E2.Job
FROM emp e1 , emp e2
WHERE e1.MGR = e2.EmpNo AND E2.DeptNo IN (10,20);


-- 3.WAQTD NAME OF THE EMP AND MANAGERS SALARY IF EMPLOYEE AND MANAGER BOTH EARN MORE THAN 2300
SELECT E1.Ename , E2.Ename, E2.Sal
FROM emp e1 , emp e2
WHERE e1.MGR = e2.EmpNO AND E1.Sal > 2300 AND E2.Sal > 2300 ;

-- 4.WAQTD EMP NAME AND MANAGER'S HIREDATE IF EMPLOYEE WAS HIRED BEFORE 1982
SELECT E1.Ename , E2.HireDate
FROM emp e1 , emp e2
WHERE e1.MGR = e2.EmpNO AND E1.HireDate < '1982-01-01' ;

-- 5.WAQTD EMP NAME AND MANAGER'S COMM IF EMPLOYEE WORKS AS SALESMAN AND MANAGER WORKS IN DEPT 30
SELECT E1.Ename , E2.COMM
FROM emp e1 , emp e2
WHERE e1.MGR = e2.EmpNO AND E1.job = 'Salesman' AND E2.DeptNo = 30 ;

-- 6.WAQTD EMP NAME AND MANAGER NAME AND THEIR SALARIES IF EMPLOYEE EARNS MORE THAN MANAGER
SELECT E1.Ename , E2.Ename, E2.Sal
FROM emp e1 , emp e2
WHERE e1.MGR = e2.EmpNO AND E1.Sal > E2.Sal ;

-- 7.WAQTD EMP NAME AND HIREDATE MANAGER NAME AND HIREDATE IF MANAGER WAS HIRED BEFORE EMPLOYEE
SELECT E1.Ename , E1.HireDate, E2.Ename , E2.HireDate
FROM emp e1 , emp e2
WHERE e1.MGR = e2.EmpNO AND E2.HireDate < E1.HireDate ; 