use employee;

-- ASSIGNMENT ON EMP AND MANAGER RELATION

-- 1.WAQTD SMITHS REPORTING MANAGER'S NAME
SELECT Ename 
FROM emp
WHERE MGR = (SELECT EmpNo FROM emp WHERE Ename = 'SMITH');

-- 2.WAQTD ADAMS MANAGER'S MANAGER NAME
SELECT Ename 
FROM emp
WHERE EmpNo = (SELECT MGR FROM emp WHERE Ename = 'ADAMS');

-- 3.WAQTD DNAME OF JONES MANAGER
SELECT Dname 
FROM Dept
WHERE DeptNo IN (SELECT DeptNo FROM emp WHERE MGR = (SELECT EmpNo FROM emp WHERE Ename = 'Jones')); 

-- 4.WAQTD MILLER'S MANAGER'S SALARY
SELECT Sal 
FROM emp 
WHERE EmpNO = (SELECT MGR FROM emp WHERE Ename = 'Miller');

-- 5.WAQTD LOC OF SMITH'S MANAGER'S MANAGER.
SELECT Loc 
FROM Dept 
WHERE DeptNo IN (SELECT DeptNo FROM emp WHERE EmpNo =  (SELECT MGR FROM emp WHERE Ename = 'SMITH'));

-- 6.WAQTD NAME OF THE EMPLOYEES REPORTING TO BLAKE
SELECT Ename
FROM emp 
WHERE EmpNo = (SELECT MGR FROM emp WHERE Ename = 'BLAKE');

-- 7.WAQTD NUMBER OF EMPLPOYEES REPORTING TO KING
SELECT COUNT(EmpNo)
FROM emp
WHERE EmpNo = (SELECT MGR FROM emp WHERE EName = 'KING');

-- 8.WAQTD DETAILS OF THE EMPLOYEES REPORTING TO JONES
SELECT * 
FROM emp 
WHERE MGR = (SELECT EmpNo FROM emp WHERE Ename = 'JONES');

-- 9.WAQTD ENAMES OF THE EMPLOYEES REPORTING TO BLAKE'S MANAGER
SELECT Ename
FROM emp 
WHERE EmpNo = (SELECT MGR FROM emp WHERE Ename = 'BLAKE');

-- 10.WAQTD NUMBER OF EMPLOYEES REPORTING TO FORD'S MANAGER
SELECT COUNT(EmpNO)
FROM emp 
WHERE EmpNo = (SELECT MGR FROM emp WHERE Ename = 'FORD');


------------------------------------------------------------------------------------------------------------------------------------------------------------

-- ASSIGNMENT ON INNER JOIN :


-- 1. NAME OF THE EMPLOYEE AND HIS LOCATION OF ALL THE EMPLOYEES.
SELECT EName , Loc
FROM EMP INNER JOIN Dept
ON emp.DeptNo = Dept.DeptNO;

-- 2. WAQTD DNAME AND SALARY FOR ALL THE EMPLOYEE WORKING IN ACCOUNTING.
SELECT DName , Sal
FROM emp INNER JOIN dept
ON emp.DeptNo = Dept.DeptNO
WHERE Dept.Dname = 'ACCOUNTING';

-- 3. WAQTD DNAME AND ANNUAL SALARY FOR ALL EMPLOYEES WHOS SALARY IS MORE THAN 2340
SELECT Dname, Sal*12 AS "ANNUAL SALARY"
FROM emp INNER JOIN dept
ON emp.DeptNo = Dept.DeptNO
WHERE emp.Sal > 2340;

-- 4. WAQTD ENAME AND DNAME FOR EMPLOYEES HAVING CAHARACTER 'A' IN THEIR DNAME
SELECT Ename , DName
FROM emp INNER JOIN dept
ON emp.DeptNo = Dept.DeptNO
WHERE Dept.Dname LIKE '%A%';  

-- 5. WAQTD ENAME AND DNAME FOR ALL THE EMPLOYEES WORKING AS SALESMAN
SELECT EName , DName 
FROM emp INNER JOIN dept 
ON emp.DeptNo = Dept.DeptNO
WHERE Emp.Job = 'SALESMAN';

-- 6. WADTD DNAME AND JOB FOR ALL THE EMPLOYEES WHOS JOB AND DNAME STARTS WITH CHARACTER 'S'
SELECT Dname, Job
FROM emp INNER JOIN dept 
ON emp.DeptNo = Dept.DeptNO
WHERE JOB LIKE 'S%' AND DName LIKE 'S%';

-- 7. WAQTD DNAME AND MGR NO FOR EMPLOYEES REPORTING TO 7839
SELECT DName, MGR
FROM Emp INNER JOIN dept
ON emp.DeptNo = Dept.DeptNO
WHERE emp.MGR = 7839 ;
 
-- 8. WAQTD DNAME AND HIREDATE FOR EMPLOYEES HIRED AFTER 83 INTO ACCOUNTING OR RESEARCH DEPT
SELECT Dname , HireDate 
FROM emp INNER JOIN dept
ON emp.DeptNo = Dept.DeptNO
WHERE emp.HireDate > '1983-12-31' AND dept.Dname IN ('ACCOUNTING','RESEARCH');

-- 9. WAQTD ENAME AND DNAME OF THE EMPLOYEES WHO ARE GETTING COMM IN DEPT 10 OR 30
SELECT Ename, Dname
FROM emp INNER JOIN dept
ON emp.DeptNo = Dept.DeptNO
WHERE emp.Comm IS NOT NULL AND emp.DeptNO IN (10,30);

-- 10. WAQTD DNAME AND EMPNO FOR ALL THE EMPLOYEES WHO'S EMPNO ARE (7839,7902) AND ARE WORKING IN LOC NEW YORK
SELECT DName , EmpNO , Loc
FROM emp INNER JOIN dept
ON emp.DeptNo = Dept.DeptNO
WHERE Emp.EmpNo IN (7839,7902) AND dept.Loc = 'NEW YORK';


